# Generated by Django 4.2.7 on 2023-12-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkincheckout',
            name='check_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
